// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NB.KingOfBeers.Database.Context;

#nullable disable

namespace NB.KingOfBeers.Database.Migrations
{
    [DbContext(typeof(KobDataContext))]
    [Migration("20230621135055_BreweryBeer")]
    partial class BreweryBeer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.Bar", b =>
                {
                    b.Property<int>("BarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BarId");

                    b.ToTable("Bar");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.Beer", b =>
                {
                    b.Property<int>("BeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BreweryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentageAlcoholByVolume")
                        .HasColumnType("TEXT");

                    b.HasKey("BeerId");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beer");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.Brewery", b =>
                {
                    b.Property<int>("BreweryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BarId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BreweryId");

                    b.HasIndex("BarId");

                    b.ToTable("Brewery");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.BreweryBeers", b =>
                {
                    b.Property<int>("BreweryBeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BreweryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BreweryBeerId");

                    b.HasIndex("BeerId");

                    b.HasIndex("BreweryId");

                    b.ToTable("BreweryBeer");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.Beer", b =>
                {
                    b.HasOne("NB.KingOfBeers.Database.Models.Brewery", null)
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.Brewery", b =>
                {
                    b.HasOne("NB.KingOfBeers.Database.Models.Bar", null)
                        .WithMany("Breweries")
                        .HasForeignKey("BarId");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.BreweryBeers", b =>
                {
                    b.HasOne("NB.KingOfBeers.Database.Models.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NB.KingOfBeers.Database.Models.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.Bar", b =>
                {
                    b.Navigation("Breweries");
                });

            modelBuilder.Entity("NB.KingOfBeers.Database.Models.Brewery", b =>
                {
                    b.Navigation("Beers");
                });
#pragma warning restore 612, 618
        }
    }
}
